### PR TITLE
[INCR-89] python-modernize -w edxval manage.py setup.py urls.py

### PR DESCRIPTION
**Pull request by singuliere**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @singuliere! I've created [OSPR-3199](https://openedx.atlassian.net/browse/OSPR-3199) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@singuliere Thank you for your contribution. @edx/incr-reviewers Can you give this a look?

**Comment by edx-webhook** [comment]
@singuliere 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-val&entry.867055334=https://github.com/edx/edx-val/pull/172&entry.1484655318=https://github.com/singuliere&entry.752974735=2019-03-13+11:44&entry.1917517419=2019-03-15+16:03&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by singuliere** [comment]
@michaelyoungstrom thanks. So nice to have a PR merge before starting the week-end :sparkles:

**Pull request merged**
