### PR TITLE
Updating enum43 to support Python3 versions

### PR DESCRIPTION
**Pull request by ahmedaljazzar**
This will save us from the following error

```PYTHON
    AttributeError: module 'enum' has no attribute 'IntFlag'
```

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ahmedaljazzar! I've created [OSPR-1830](https://openedx.atlassian.net/browse/OSPR-1830) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-val/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@ahmedaljazzar Can you resolve the merge conflict? Thanks.

**Comment by ahmedaljazzar** [comment]
@gsong The conflicts have been resolved :D

**Comment by sanfordstudent** [comment]
Hi @ahmedaljazzar - I'm taking a look at this PR, and it looks pretty straightforward. Before we merge it, I'd appreciate you squashing it to one commit and rebasing onto master. Then I'll approve it and we'll be ready to go!

Thanks!

**Comment by ahmedaljazzar** [comment]
Hi @sanfordstudent, just squashed the commits and updated the PR.

Thanks!

**Pull request merged**
