### PR TITLE
Update tox.ini (for INCR-71)

### PR DESCRIPTION
**Pull request by gjanesch**
The modifications to tox.ini as specified in [INCR-71](https://openedx.atlassian.net/browse/INCR-71?page=com.atlassian.streams.streams-jira-plugin:activity-stream-issue-tab) have been added.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @gjanesch! I've created [OSPR-3061](https://openedx.atlassian.net/browse/OSPR-3061) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@gjanesch Thank you for your contribution. Please let me know once tests pass and it is ready to be looked at.

**Comment by gjanesch** [comment]
I think I'm not understanding something here (possibly because I'm fairly new to contributing to open source), so I've got a couple of questions.

1.) INCR-71 says that removing support for Django 1.8 and 1.10 from tox.ini is something that can be done, so I did that, but it looks like the Travis CI build still wants them.  Was that wrong, or is the CI tool working off of old information?

2.) I'm still getting one failure on test, but INCR-71 says that it's okay if not everything passes.  Is that the case?  For the record, here's the traceback of the error (I'm using a virtual environment named "edx-venv"):

> Traceback (most recent call last):
>   File "/Users/Me/Desktop/Projects/edx-val/edx-venv/src/djangorestframework/rest_framework/compat.py", line 22, in <module>
>     from django.urls import (
> ImportError: cannot import name 'RegexURLPattern'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/Me/Desktop/Projects/edx-val/edx-venv/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
>     raise self.exc_val.with_traceback(self.tb)
>   File "/Users/Me/Desktop/Projects/edx-val/edx-venv/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/Users/Me/Desktop/Projects/edx-val/edx-venv/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/Users/Me/Desktop/Projects/edx-val/edx-venv/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 245, in load_module
>     return load_package(name, filename)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 217, in load_package
>     return _load(spec)
>   File "<frozen importlib._bootstrap>", line 684, in _load
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/Users/Me/Desktop/Projects/edx-val/edxval/tests/__init__.py", line 5, in <module>
>     from rest_framework.test import APITestCase
>   File "/Users/Me/Desktop/Projects/edx-val/edx-venv/src/djangorestframework/rest_framework/test.py", line 20, in <module>
>     from rest_framework.compat import coreapi, requests
>   File "/Users/Me/Desktop/Projects/edx-val/edx-venv/src/djangorestframework/rest_framework/compat.py", line 26, in <module>
>     from django.core.urlresolvers import (  # Will be removed in Django 2.0
> ModuleNotFoundError: No module named 'django.core.urlresolvers'

**Comment by natabene** [comment]
> I think I'm not understanding something here (possibly because I'm fairly new to contributing to open source), so I've got a couple of questions.
> 
> 1.) INCR-71 says that removing support for Django 1.8 and 1.10 from tox.ini is something that can be done, so I did that, but it looks like the Travis CI build still wants them. Was that wrong, or is the CI tool working off of old information?
> 
> 2.) I'm still getting one failure on test, but INCR-71 says that it's okay if not everything passes. Is that the case? For the record, here's the traceback of the error (I'm using a virtual environment named "edx-venv"):
> 
> > Traceback (most recent call last):
> > File "/Users/Me/Desktop/Projects/edx-val/edx-venv/src/djangorestframework/rest_framework/compat.py", line 22, in 
> > from django.urls import (
> > ImportError: cannot import name 'RegexURLPattern'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/Users/Me/Desktop/Projects/edx-val/edx-venv/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
> > raise self.exc_val.with_traceback(self.tb)
> > File "/Users/Me/Desktop/Projects/edx-val/edx-venv/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
> > addr.filename, addr.module)
> > File "/Users/Me/Desktop/Projects/edx-val/edx-venv/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
> > return self.importFromDir(dir_path, fqname)
> > File "/Users/Me/Desktop/Projects/edx-val/edx-venv/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
> > mod = load_module(part_fqname, fh, filename, desc)
> > File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 245, in load_module
> > return load_package(name, filename)
> > File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 217, in load_package
> > return _load(spec)
> > File "", line 684, in _load
> > File "", line 665, in _load_unlocked
> > File "", line 678, in exec_module
> > File "", line 219, in _call_with_frames_removed
> > File "/Users/Me/Desktop/Projects/edx-val/edxval/tests/**init**.py", line 5, in 
> > from rest_framework.test import APITestCase
> > File "/Users/Me/Desktop/Projects/edx-val/edx-venv/src/djangorestframework/rest_framework/test.py", line 20, in 
> > from rest_framework.compat import coreapi, requests
> > File "/Users/Me/Desktop/Projects/edx-val/edx-venv/src/djangorestframework/rest_framework/compat.py", line 26, in 
> > from django.core.urlresolvers import (  # Will be removed in Django 2.0
> > ModuleNotFoundError: No module named 'django.core.urlresolvers'

@jmbowman Could you help @gjanesch out with questions in the comment above?

**Comment by jmbowman** [comment]
The `.travis.yml` file also needs to be updated to remove the Django 1.8 and 1.10 tests from CI; sorry that wasn't clear in the ticket description.

And yes, it's ok if the tests don't pass yet with Python 3.6 or the newer Django versions; honestly the main point of this ticket was just to make the `tox.ini` and `.travis.yml` updates to let us start identifying the problems with Python 3 and Django2+ support.  I need to start emphasizing that in the ticket descriptions, since people keep getting excited and going on to start fixing the problems. 😄 

That test failure you saw is because edx-val still specifies an [outdated fork of djangorestframework](https://github.com/edx/edx-val/blob/9f9994b3eb5866217fec4ebff3b2404e4c6966f6/requirements/base.in#L7) which doesn't support the newer Django versions yet.  Again, you don't have to fix that with this pull request, I'll write up some additional tickets to upgrade the dependencies and do further cleanup.

**Comment by gjanesch** [comment]
Alright, I've updated the yml file.  Is there anything else that I've missed?

**Comment by jmbowman** [comment]
The new Travis test runs involving Python 3 and Django 2+ should be [allowed to fail](https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail).  I didn't get into that in the ticket description because I wasn't planning to add them to Travis just yet, but this does let us see what the current problems are in those configurations while still allowing PRs that work under Python 2.7 and Django 1.11 to be merged.

**Comment by gjanesch** [comment]
Looks like that's got it.

Thanks for all your help Jeremy, I appreciate your patience.

**Comment by edx-webhook** [comment]
@gjanesch 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-val&entry.867055334=https://github.com/edx/edx-val/pull/168&entry.1484655318=https://github.com/gjanesch&entry.752974735=2019-02-10+00:56&entry.1917517419=2019-02-17+03:32&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
