### PR TITLE
PLAT-612: Fix VAL error on re-import

### PR DESCRIPTION
**Pull request by nasthagiri**
@gwprice @adampalay Please review.

@adampalay The requirements.txt file in edx-platform will need to be updated to take this change.

### CODE REVIEW

**Comment by adampalay** [comment]
@Shrhawk

**Comment by Shrhawk** [comment]
@adampalay is we need test for studio also ?

**Comment by adampalay** [comment]
@Shrhawk , I think this is good!

**Comment by gwprice** [comment]
I think get_or_create_with_validation should mimic the interface of get_or_create (i.e. it should return the object and whether it was created)

**Comment by nasthagiri** [comment]
Updated.  Please review again.

**Comment by gwprice** [comment]
:+1:

**Comment by Shrhawk** [comment]
:+1:  working fine now

**Comment by adampalay** [comment]
@nasthagiri should we open a PR to edx-platform to update edx-val, or does this happen routinely before each edx-platform release?

**Comment by nasthagiri** [comment]
@adampalay Please open a PR.  And, as @Shrhawk suggests, if possible, add a unit test for reimporting a course with a video module (that fails before the PR and succeeds with the PR).

**Comment by nasthagiri** [comment]
We don't update edx-val automatically or routinely.  Thanks.

**Comment by adampalay** [comment]
got it

**Pull request merged**
