### PR TITLE
[INCR-89] Run python-modernize on edxval

### PR DESCRIPTION
**Pull request by cclauss**
Fixes: https://openedx.atlassian.net/browse/INCR-89

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @cclauss! I've created [OSPR-3151](https://openedx.atlassian.net/browse/OSPR-3151) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@cclauss Thank you for your contribution. Please let me know once checks are green.

**Comment by natabene** [comment]
@cclauss I am curious if you are still interested in pursuing this. If yes, please let me know if you need any help.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @cclauss! I've created [OSPR-3512](https://openedx.atlassian.net/browse/OSPR-3512) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by edx-webhook** [comment]
@cclauss Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-val&entry.867055334=https://github.com/edx/edx-val/pull/171&entry.1484655318=https://github.com/cclauss&entry.752974735=2019-02-28+04:58&entry.1917517419=2019-05-21+22:02&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
